openapi: 3.0.3
info:
  title: Fleet Clearance API
  description: |-
    By using the Fleet Clearance API endpoints, it's possible for fleet operators to activate and deactivate data access to their vehicles.
    
    In order to use the API endpoints you will need to retrieve an access token using the [OAuth API](/api-references/code-references/oauth2/reference/v1/) with `client_credentials` grant
    
    * Sandbox server: `https://sandbox.api.high-mobility.com`
    * Production server: `https://api.high-mobility.com`

  contact:
    email: support@high-mobility.com
  version: 1.0.0
externalDocs:
  description: High Mobility's Developer Console
  url: https://www.high-mobility.com
servers:
  - url: https://sandbox.api.high-mobility.com
  - url: https://api.high-mobility.com

paths:
  /v1/fleets/vehicles:
    post:
      summary: Create a clearance
      security:
        - FleetClearanceAuth:
          - fleet:clearance
      tags:
        - Fleet Clearance Resource
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FleetVehicleRequest'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FleetVehiclePostResponse'
          description: Success
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClearanceUnauthorizedErrors'
          description: When an invalid ServiceAccountToken is used.
        '403':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FleetForbiddenErrors'
          description: When the application doesn't have fleet access.
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FleetErrors'
          description: >-
            Invalid Input. It occurs when the payload is missing a params or the
            the application is not configured.
        '500':
          description: Server Errors


    get:
      summary: Get all clearances
      security:
        - FleetClearanceAuth:
          - fleet:clearance
      tags:
        - Fleet Clearance Resource
      parameters:
        - in: query
          name: filter
          schema:
            type: object
          required: false
          description: URL Encoded JSON
          examples:
            vin_eq:
              summary: Filter by VIN - Equality
              value:
                vin:
                  operator: eq
                  value: EXVETESTVIN000001
            vin_in:
              summary: Filter by VIN - Inclusion
              value:
                vin:
                  operator: in
                  value:
                    - EXVETESTVIN000001
                    - EXVETESTVIN000002
            status_eq:
              summary: Filter by Status - Equality
              value:
                status:
                  operator: eq
                  value: approved
            status_in:
              summary: Filter by Status - Inclusion
              value:
                status:
                  operator: in
                  value:
                    - approved
                    - rejected
            tags_eq:
              summary: Filter by Tags - Equality
              value:
                tags:
                  operator: eq
                  value:
                    some_key: some_value
            tags_contains:
              summary: Filter by Tags - Contains
              value:
                tags:
                  operator: contains
                  value:
                    some_key: some_value
            brand_eq:
              summary: Filter by Brand - Equality
              value:
                brand:
                  operator: eq
                  value: bmw
            brand_in:
              summary: Filter by Brand - Inclusion
              value:
                brand:
                  operator: in
                  value:
                    - bmw
                    - mercedes-benz
            approved_at_eq:
              summary: Filter by Approval Date - Equality
              value:
                approved_at:
                  operator: eq
                  value: "1999-03-31T00:00:00Z"
            approved_at_lt:
              summary: Filter by Approval Date - Less than
              value:
                approved_at:
                  operator: lt
                  value: "1999-03-31T00:00:00Z"
            approved_at_gt:
              summary: Filter by Approval Date - Greater than
              value:
                approved_at:
                  operator: gt
                  value: "1999-03-31T00:00:00Z"
            approved_at_lte:
              summary: Filter by Approval Date - Less than or Equal
              value:
                approved_at:
                  operator: lte
                  value: "1999-03-31T00:00:00Z"
            approved_at_gte:
              summary: Filter by Approval Date - Greater than or Equal
              value:
                approved_at:
                  operator: gte
                  value: "1999-03-31T00:00:00Z"
            inserted_at_eq:
              summary: Filter by Insertion Date - Equality
              value:
                inserted_at:
                  operator: eq
                  value: "1999-03-31T00:00:00Z"
            inserted_at_lt:
              summary: Filter by Insertion Date - Less than
              value:
                inserted_at:
                  operator: lt
                  value: "1999-03-31T00:00:00Z"
            inserted_at_gt:
              summary: Filter by Insertion Date - Greater than
              value:
                inserted_at:
                  operator: gt
                  value: "1999-03-31T00:00:00Z"
            inserted_at_lte:
              summary: Filter by Insertion Date - Less than or Equal
              value:
                inserted_at:
                  operator: lte
                  value: "1999-03-31T00:00:00Z"
            inserted_at_gte:
              summary: Filter by Insertion Date - Greater than or Equal
              value:
                inserted_at:
                  operator: gte
                  value: "1999-03-31T00:00:00Z"
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FleetVehicleGetResponse'
          description: Success
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClearanceUnauthorizedErrors'
          description: When an invalid ServiceAccountToken is used.
        '403':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FleetForbiddenErrors'
          description: When the application doesn't have fleet access.
        '500':
          description: Server Errors
      description: >-
        Get the status of VINs that have previously been registered for data
        access clearance.

  /v1/fleets/vehicles/{vin}:
    get:
      summary: Get clearance for a vin
      security:
        - FleetClearanceAuth:
          - fleet:clearance
      tags:
        - Fleet Clearance Resource
      parameters:
        - name: vin
          in: path
          required: true
          schema:
            type: string
          description: VIN of the vehicle in question.

      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FleetVehicleGetItemResponse'
          description: Success
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClearanceUnauthorizedErrors'
          description: When an invalid ServiceAccountToken is used.
        '403':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FleetForbiddenErrors'
          description: When the application doesn't have fleet access.
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FleetErrors'
          description: Given resource not found
        '500':
          description: Server Errors

      description: >-
        Get the status of a VIN that has previously been registered for data
        access clearance.

    delete:
      summary: Delete clearance
      security:
        - FleetClearanceAuth:
          - fleet:clearance
      tags:
        - Fleet Clearance Resource
      parameters:
        - name: vin
          in: path
          required: true
          schema:
            type: string
          description: VIN of the vehicle in question.
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FleetVehicleDeleteItemResponse'
          description: Success
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClearanceUnauthorizedErrors'
          description: When an invalid ServiceAccountToken is used.
        '403':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FleetForbiddenErrors'
          description: When the application doesn't have fleet access.
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FleetErrors'
          description: Given resource not found
        '409':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FleetDeletionErrors'
          description: >-
            When deleting a clearance with given VIN is not possible.
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FleetCancellationErrors'
          description: >-
            When cancellation is not possible at this moment.
        '500':
          description: Server Errors

      description: >-
        Delete the clearance for the given VIN. If the vehicle is in approved state, a revoke is performed. If the clearance is in pending state, the activation process is canceled. **The cancelation is currently supported for Mercedes-Benz, Volkswagen, Audi, Skoda, SEAT, CUPRA and the Stellantis brands.**

  /v1/fleets/{vin}/cancel_activation:
    post:
      summary: Cancel clearance
      deprecated: true
      security:
        - FleetClearanceAuth:
          - fleet:clearance
      tags:
        - Fleet Clearance Resource
      parameters:
        - name: Authorization
          in: header
          description: 'Bearer token'
          required: true
          schema:
            type: string
        - name: vin
          in: path
          required: true
          schema:
            type: string
          description: VIN of the vehicle in question.
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FleetVin'
          description: ''
        '500':
          description: Server Errors

      description: >-
        Deprecated: use DELETE /v1/fleet/vehicles/{vin} end point instead

  /v1/fleets/access_tokens:
    post:
      summary: Get access token
      deprecated: true
      security:
        - FleetClearanceAuth:
          - fleet:clearance
      tags:
        - Fleet Clearance Resource
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccessTokensResponse'
          description: Success
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccessTokensError'
          description: Error
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClearanceUnauthorizedErrors'
          description: When an invalid ServiceAccountToken is used.
        '403':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FleetErrors'
          description: When the application doesn't have fleet access.
        '500':
          description: Server Errors
      description: >-
        Creates an access token for a VIN that has the "approved" state. This
        access token can be used to retrieve car data through any of the SDKs or
        the REST API.


components:
  schemas:
    FleetVehicleGetResponse:
      type: array
      title: FleetVehicleGetResponse
      items:
        $ref: '#/components/schemas/FleetVehicleGetItemResponse'
      example:
        - vin: VIN0TESTVIN000000
          status: approved
          brand: mercedes-benz
          tags:
            foo: bar
            bar: baz
          changelog:
            - timestamp: "2022-03-22T09:36:51"
              status: pending
            - timestamp: "2022-03-22T10:36:51"
              status: approved

    FleetForbiddenErrors:
      type: object
      title: Errors
      properties:
        errors:
          description: List of errors
          type: array
          items:
            $ref: '#/components/schemas/Error'
          example:
            - detail: This service account is not associated with a fleet.
              source: Authorization
              title: Forbidden

    ClearanceUnauthorizedErrors:
      type: object
      title: Errors
      properties:
        errors:
          description: List of errors
          type: array
          items:
            $ref: '#/components/schemas/Errors'
          example:
            - detail: >
                Missing or invalid authorization header. The token must be
                obtained through the service account API and sent as a header with
                the format "Authorization: Bearer <token>"
              source: Authorization
    Errors:
      type: array
      title: Errors
      items:
        $ref: '#/components/schemas/Error'
      description: List of errors
    Error:
      type: object
      title: Error
      required:
        - title
      properties:
        title:
          type: string
          description: Error title
        source:
          type: string
          description: Field that has problem
        detail:
          type: string
          description: Error detail
      description: Error details

    FleetVehicleRequest:
      type: object
      properties:
        vehicles:
          type: array
          items:
            $ref: '#/components/schemas/FleetVehicle'
          description: Vehicle list
      example:
        vehicles:
          - vin: WBADT43452G296403
            brand: mercedes-benz
            tags: {}
          - vin: WBADT43452G296404
            brand: bmw
            tags: {}
          - vin: VIN012345678901234
            brand: ds
            tags: {}
          - vin: VIN01234567890123
            brand: unknown
            tags:
              foo: bar
              bar: baz
      required:
        - vehicles


    FleetVehicle:
      type: object
      title: FleetVehicle
      required:
        - vin
        - brand
      properties:
        vin:
          type: string
          description: Vehicle Identification Number (VIN)
        brand:
          type: string
          enum:
            - bmw
            - citroen
            - ds
            - mercedes-benz
            - mini
            - opel
            - peugeot
            - vauxhall
            - jeep
            - fiat
            - alfaromeo
            - ford
            - renault
            - dacia
            - toyota
            - lexus
            - porsche
            - maserati
            - kia
            - tesla
            - volvo-cars
            - skoda
            - audi
            - volkswagen
            - seat
            - cupra
            - sandbox
          description: Vehicle Brand
        control_measures:
          deprecated: true
          type: object
          properties:
            odometer:
              required:
                - value
                - unit
              type: object
              properties:
                value:
                  type: integer
                unit:
                  type: string
                  enum:
                    - kilometers
                    - miles
        tags:
          type: object
          additionalProperties:
            type: string

    FleetVehiclePostResponse:
      type: object
      title: FleetVehiclePostResponse
      required:
        - vehicles
      properties:
        vehicles:
          type: array
          items:
            $ref: '#/components/schemas/FleetVin'
          description: Vehicle list
      example:
        vehicles:
          - vin: WBADT43452G296403
            status: pending
            tags: {}
          - vin: WBADT43452G296404
            status: pending
            tags:
              foo: bar
              bar: baz
          - vin: VIN012345678901234
            status: error
            description: vin should be 17 character(s)
          - vin: VIN0123456789012
            status: error
            description: The brand is invalid


    FleetVin:
      type: object
      title: FleetVin
      required:
        - vin
        - status
      properties:
        vin:
          type: string
          description: Vehicle Identification Number (VIN)
        status:
          type: string
          enum:
            - approved
            - pending
            - revoked
            - rejected
            - revoking
            - canceling
            - canceled
            - error
          description: >-
            An access token can be retrieved for the FleetVin if the status is
            "approved"
        description:
          type: string
          description: Optional description of the VIN
        tags:
          type: object
          additionalProperties:
            type: string
      example:
        vin: WBADT43452G296403
        status: pending
        tags:
          foo: bar
          bar: baz

    FleetErrors:
      type: object
      title: Errors
      properties:
        errors:
          description: List of errors
          type: array
          items:
            $ref: '#/components/schemas/Error'

    FleetVehicleGetItemResponse:
      type: object
      title: FleetVehicle
      required:
        - vin
        - status
      properties:
        vin:
          type: string
          description: Vehicle Identification Number (VIN)
        status:
          type: string
          enum:
            - approved
            - pending
            - revoking
            - revoked
            - rejected
            - canceling
            - canceled
        brand:
          type: string
          enum:
            - bmw
            - citroen
            - ds
            - mercedes-benz
            - mini
            - opel
            - peugeot
            - vauxhall
            - jeep
            - fiat
            - alfaromeo
            - ford
            - renault
            - dacia
            - toyota
            - lexus
            - porsche
            - maserati
            - kia
            - tesla
            - volvo-cars
            - skoda
            - audi
            - volkswagen
            - seat
            - cupra   
            - sandbox
        changelog:
           type: array
           items:
             $ref: '#/components/schemas/FleetVinChangelog'
        tags:
          type: object
          additionalProperties:
            type: string

    FleetVinChangelog:
      type: object
      required:
        - timestamp
        - status
      properties:
        timestamp:
          type: string
          description: 'Date and Time in ISO8601 format example: ''2018-11-06T10:20:37.094533Z'''
        status:
          type: string
          enum:
            - approved
            - pending
            - revoking
            - revoked
            - rejected
            - canceling
            - canceled
        reason:
          type: string
          description: 'Reason for rejection'

    FleetDeletionErrors:
      type: object
      title: Errors
      properties:
        errors:
          description: List of errors
          type: array
          items:
            $ref: '#/components/schemas/Error'
          example:
            - detail: Clearance is already removed
              source: vin
              title: Conflict
            - detail: Clearance is in transition mode
              source: vin
              title: Conflict


    FleetCancellationErrors:
      type: object
      title: Errors
      properties:
        errors:
          description: List of errors
          type: array
          items:
            $ref: '#/components/schemas/Error'
          example:
            - detail: cancellation is not supported for this vin
              source: vin
              title: not supported
            - detail: the pending status could only be canceled after 1 day it's created
              source: status
              title: too early

    FleetVehicleDeleteItemResponse:
      type: object
      title: FleetVehicle
      required:
        - vin
        - status
      properties:
        vin:
          type: string
          description: Vehicle Identification Number (VIN)
        status:
          type: string
          enum:
            - revoking
            - canceling
        tags:
          type: object
          additionalProperties:
            type: string
      example:
        vin: VIN0TESTVIN000000
        status: revoking
        tags:
          foo: bar
          bar: baz


    AccessTokensResponse:
      type: object
      title: AccessTokensResponse
      required:
        - expires_in
        - access_token
        - token_type
      properties:
        validity_start_date:
          type: string
          description: 'Date and Time in ISO8601 format example: ''2018-11-06T10:20:37.094533Z'''
        validity_end_date:
          type: string
          description: 'Date and Time in ISO8601 format example: ''2018-11-06T10:20:37.094533Z'''
        token_type:
          type: string
          description: Token type
        scope:
          type: string
          description: List of scopes
        refresh_token:
          type: string
          description: Refresh token
        expires_in:
          type: integer
          description: Expiration time in seconds
        access_token:
          type: string
          description: Access token
      example:
        token_type: bearer
        scope: >-
          diagnostics.get.mileage door_locks.get.locks
          windows.get.windows_positions
        refresh_token: 7f7a9be0-04c9-4202-a59f-35d55079b6ba
        expires_in: 600
        access_token: a50e89e5-093c-4727-8101-4c6e81addabe
      description: Access Tokens
    FleetAccessTokensRequest:
      type: object
      properties:
        vin:
          type: string
          description: The VIN of the vehicle to ask access to.
      example:
        vin: WBADT43452G296403
      required:
        - vin
    AccessTokensError:
      type: object
      title: AccessTokensError
      required:
        - error
      properties:
        error_description:
          type: string
          description: Error description
        error:
          type: string
          description: Error code
      description: Error details

  securitySchemes:
    FleetClearanceAuth:
      flows:
        clientCredentials:
          scopes:
            fleet:clearance: fleet clearance
          tokenUrl: https://api.sandbox.high-mobility.com/v1/access_token
      type: oauth2
